config/routes.rb
Rails.application.routes.draw do
  get '/' => 'users#index'
  resources :users, only: [:show, :index] do
    resources :products, only: [:index, :new, :create, :show]
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :users
	validates :title, presence: true
	validates :description, presence: true
	validates :deadline, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :products
	validates :email, presence: true, uniqueness: true 	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :set_user
	def index
		@products = @user.products.all
	end

	def show
		@product = Product.find_by(id: params[:id])
	end

	private

	def set_user
		@user = User.find_by(id: params[:user_id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ebid</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<h1> Here's a list of <%= @user.name %>'s  products </h1>
<ul>
	<% @products.each do |product| %>
		<li><%= link_to product.title, user_product_path(:user_id => @user.id, :id => product.id) %></li>
	<% end %>
</ul>

	

app/views/products/show.html.erb
<h1>Details for <%= @product.title %> </h1>

<p><%= @product.description %></p>
<p><%= @product.deadline %></p>

app/views/users/index.html.erb
<h1> Welcome to Ebid </h1>
<span><h2> An online auction house for everything</h2></span>

<ul>
	<% @users.each do |user| %>
		
		<li> <%= link_to user.name, user_products_path(:user_id => user.id)  %> </li>
	<% end %>
</ul>